### ISSUE TITLE
reviewing desktop view

### ISSUE THREAD

**Issue by saied2035** [ahangarha/Portfolio#7]
### reviewing the PR : https://github.com/ahangarha/Portfolio/pull/4

**Comment by Mehdi-Rh** [comment]
Great work so far, I think capitalizing your commits give more professionalism to your work.

**Comment by thenarain** [comment]
It is an impressive piece of work.

**Comment by saied2035** [comment]
## **it's really a great work you did 💯 , but just two things I noticed :** 
- **sometimes you use div tag but you don't need it like in header tag you used a div tag as a container of the elements to positioning them properly but you can directly posoitioning them.**
- **sometimes you give classes with id to the same tag and just make all the css in just the class or the id make sure that you didn't add unecessary clas or id**

 ***again, you really built a great portfolio project. I  wish you the best 🥇***

**Comment by ahangarha** [comment]
Thank you everybody for your feedback.

> sometimes you use div tag but you don't need it like in header tag you used a div tag as a container of the elements to positioning them properly but you can directly posoitioning them.

Actually I needed this to make sure the content of the given section doesn't go beyond some certain width. I think we didn't use this in Contact section because its design was so simple to adjust but for others I didn't know how to do it. If it some particular case you think I did extra, would be great to mention.

> sometimes you give classes with id to the same tag

For sections, I used tag to be more specific in styling them and used general class to make them follow the general rules for container. But I know it was not necessary to use id for form inputs. If you mean this, I agree with you. Those ids could be removed.

Thanks again for feedback.
